<a href="https://colab.research.google.com/github/TheAraibKhan/Natural-Language-Processing-Lab/blob/main/NLP_Practical_14_WMD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Natural Language Processing Laboratory
#
# Practical 14: Text Similarity using Word Mover's Distance (WMD)
#
# Name: Araib Khan
# Course: B.Tech CSE (Artificial Intelligence)
# Subject: Natural Language Processing Laboratory
# Practical No.: 14
# CO: CO2
#
# Objective:
# To compute the Word Mover's Distance between text documents using
# pre-trained word embeddings and analyze their semantic similarity.

In [2]:
!pip install -q gensim POT

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.2/44.2 kB 556.6 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 41.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 32.9/32.9 MB 14.4 MB/s eta 0:00:00


In [3]:
import gensim.downloader as api
import numpy as np

print("Libraries imported successfully.")

Libraries imported successfully.


In [4]:
print("Loading pre-trained GloVe embeddings...")

model = api.load("glove-wiki-gigaword-50")

print("GloVe embeddings loaded successfully.")
print("Vocabulary Size:", len(model))
print("Vector Dimension:", model.vector_size)

Loading pre-trained GloVe embeddings...
[==================================================] 100.0% 66.0/66.0MB downloaded
GloVe embeddings loaded successfully.
Vocabulary Size: 400000
Vector Dimension: 50


In [5]:
document1 = "machine learning is a useful technology for data analysis"

document2 = "machine learning is useful for analyzing data"

document3 = "football players practice on the field for the game"

print("Document 1:")
print(document1)

print("\nDocument 2:")
print(document2)

print("\nDocument 3:")
print(document3)

Document 1:
machine learning is a useful technology for data analysis

Document 2:
machine learning is useful for analyzing data

Document 3:
football players practice on the field for the game


In [6]:
tokens1 = document1.lower().split()
tokens2 = document2.lower().split()
tokens3 = document3.lower().split()

print("Document 1 Tokens:")
print(tokens1)

print("\nDocument 2 Tokens:")
print(tokens2)

print("\nDocument 3 Tokens:")
print(tokens3)

Document 1 Tokens:
['machine', 'learning', 'is', 'a', 'useful', 'technology', 'for', 'data', 'analysis']

Document 2 Tokens:
['machine', 'learning', 'is', 'useful', 'for', 'analyzing', 'data']

Document 3 Tokens:
['football', 'players', 'practice', 'on', 'the', 'field', 'for', 'the', 'game']


In [7]:
def check_vocabulary(tokens, model):
    missing_words = [word for word in tokens if word not in model]
    return missing_words


print("Vocabulary Check")

missing1 = check_vocabulary(tokens1, model)
missing2 = check_vocabulary(tokens2, model)
missing3 = check_vocabulary(tokens3, model)

print("Document 1 missing words:", missing1)
print("Document 2 missing words:", missing2)
print("Document 3 missing words:", missing3)

Vocabulary Check
Document 1 missing words: []
Document 2 missing words: []
Document 3 missing words: []


In [8]:
wmd_1_2 = model.wmdistance(tokens1, tokens2)

print("Word Mover's Distance")
print("----------------------")
print(f"Document 1 vs Document 2: {wmd_1_2:.4f}")

Word Mover's Distance
----------------------
Document 1 vs Document 2: 0.2505


In [9]:
wmd_1_3 = model.wmdistance(tokens1, tokens3)

print("Word Mover's Distance")
print("----------------------")
print(f"Document 1 vs Document 3: {wmd_1_3:.4f}")

Word Mover's Distance
----------------------
Document 1 vs Document 3: 0.7914


In [10]:
wmd_2_3 = model.wmdistance(tokens2, tokens3)

print("Word Mover's Distance")
print("----------------------")
print(f"Document 2 vs Document 3: {wmd_2_3:.4f}")

Word Mover's Distance
----------------------
Document 2 vs Document 3: 0.8303


In [11]:
print("Pairwise Word Mover's Distance")
print("=" * 50)

print(f"Document 1 vs Document 2 : {wmd_1_2:.4f}")
print(f"Document 1 vs Document 3 : {wmd_1_3:.4f}")
print(f"Document 2 vs Document 3 : {wmd_2_3:.4f}")

Pairwise Word Mover's Distance
Document 1 vs Document 2 : 0.2505
Document 1 vs Document 3 : 0.7914
Document 2 vs Document 3 : 0.8303


In [12]:
documents = [tokens1, tokens2, tokens3]

distance_matrix = np.zeros((3, 3))

for i in range(3):
    for j in range(3):
        if i == j:
            distance_matrix[i][j] = 0.0
        else:
            distance_matrix[i][j] = model.wmdistance(
                documents[i],
                documents[j]
            )

print("WMD Distance Matrix:")
print(distance_matrix.round(4))

WMD Distance Matrix:
[[0.     0.2505 0.7914]
 [0.2505 0.     0.8303]
 [0.7914 0.8303 0.    ]]


In [13]:
import pandas as pd

distance_table = pd.DataFrame(
    distance_matrix,
    index=["Document 1", "Document 2", "Document 3"],
    columns=["Document 1", "Document 2", "Document 3"]
)

print("Word Mover's Distance Matrix:")
display(distance_table.round(4))

Word Mover's Distance Matrix:


,Document 1,Document 2,Document 3
Document 1,0.0000,0.2505,0.7914
Document 2,0.2505,0.0000,0.8303
Document 3,0.7914,0.8303,0.0000


In [14]:
pairs = {
    "Document 1 vs Document 2": wmd_1_2,
    "Document 1 vs Document 3": wmd_1_3,
    "Document 2 vs Document 3": wmd_2_3
}

closest_pair = min(pairs, key=pairs.get)

print("Closest Document Pair:")
print(closest_pair)

print(f"\nWMD Score: {pairs[closest_pair]:.4f}")

Closest Document Pair:
Document 1 vs Document 2

WMD Score: 0.2505


In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

text_documents = [
    document1,
    document2,
    document3
]

vectorizer = TfidfVectorizer()
tfidf_vectors = vectorizer.fit_transform(text_documents)

cosine_matrix = cosine_similarity(tfidf_vectors)

print("Cosine Similarity Matrix:")
print(cosine_matrix.round(4))

Cosine Similarity Matrix:
[[1.     0.6874 0.0474]
 [0.6874 1.     0.0527]
 [0.0474 0.0527 1.    ]]


In [16]:
print("Comparison of Similarity Measures")
print("=" * 55)

print(f"WMD - Document 1 vs Document 2 : {wmd_1_2:.4f}")
print(
    f"Cosine Similarity - Document 1 vs Document 2 : "
    f"{cosine_matrix[0][1]:.4f}"
)

print("\nNote:")
print("WMD is a distance measure, so lower values indicate greater similarity.")
print("Cosine similarity is a similarity measure, so higher values indicate greater similarity.")

Comparison of Similarity Measures
WMD - Document 1 vs Document 2 : 0.2505
Cosine Similarity - Document 1 vs Document 2 : 0.6874

Note:
WMD is a distance measure, so lower values indicate greater similarity.
Cosine similarity is a similarity measure, so higher values indicate greater similarity.


In [17]:
# Word Mover's Distance uses word embeddings to measure how much
# "movement" is required to transform the words of one document into
# the words of another document.
#
# Lower WMD:
# Documents are semantically closer.
#
# Higher WMD:
# Documents are semantically farther apart.

In [18]:
# Result:
# The Word Mover's Distance between the given documents was successfully
# calculated using pre-trained GloVe word embeddings.
#
# Pairwise distances and a complete WMD distance matrix were generated.
# The documents with more related semantic content produced lower
# WMD values than the unrelated document pair.
#
# Conclusion:
# Word Mover's Distance is an embedding-based text similarity technique
# that measures semantic distance between documents. Unlike simple
# word-overlap methods, WMD can use relationships between word vectors
# to capture semantic similarity even when documents do not contain
# exactly the same words.